language: node,
sudo: required
language: node_js
node_js:
  - "6"
env: 
  global:
    - NODE_ENV=test
branches:
  except:
  - gh-pages
  - master
script:
  - npm test
after_success: 
  - npm install -g codeclimate-test-reporter
  - npm run coveralls
  - codeclimate-test-reporter < ./coverage/lcov.info
